language: node_js
node_js: stable
script:
  - npm install
  - hexo cl
after_success:
  - git config --global user.name "happyabbi" 
  - git config --global user.email "happyabbi@gmail.com"
  - sed -i'' "/^ *repo/s~github\.com~${blog_use}@github.com~" _config.yml
  - hexo deploy